name: Welcome

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Thanks for opening your first issue! 🎉

            We'll take a look as soon as possible. In the meantime:
            - Make sure you've filled out the template completely
            - Check [existing issues](https://github.com/jovi20/typemoins/issues) for duplicates
            - Start a discussion if you need help or want feedback on an idea
          pr-message: |
            Thanks for your first pull request! 🎉

            A maintainer will review it soon. While you wait:
            - Make sure CI checks pass
            - Check the [contributing guide](https://github.com/jovi20/typemoins/blob/main/CONTRIBUTING.md)
            - Open a discussion if you want to talk through the change
